### ISSUE TITLE
Back/Cancel: how to handle this case

### ISSUE THREAD

**Issue by lexazhs** [JohnZHANGFZ/207_group_project#29]
When someone don't want to add/delete anything but accidently open the Inventory/Restriction view, how can this person get back to the logged in view.

- option 1: a new use case called 'cancel'
- option 2: get back to the logged in view by inputting nothing and clicking 'enter'
       - problem: currently, use case add_item handles this situation by giving the user a fail message: "no input, try again"

**Comment by WujiMikeChen** [comment]
I think adding a new use case is better. It's a bit more work but far more user friendly

**Comment by JohnZHANGFZ** [comment]
Yeah Option 1 would be more intuitive for users, for adding a new use case, I think it really depends the complexity of this feature, if it is complex, then an independent use case is going to very helpful and can make things clear, if it's not, maybe we can do something like adding an 'Exit' button and writing the corresponding event handling logic.
